version: 0.2

phases:

  pre_build:
    commands:
      - cd cicd
      - chmod +x install-terraform.sh terraform-cmd.sh
      - ./install-terraform.sh

  build:
    commands:
      - ./terraform-cmd.sh  
